#Sys.setlocale("LC_ALL","English")
install.packages('regbook')
install.packages('tidyverse')
install.packages('lmtest')
library(regbook)
library(tidyverse)
library(lmtest)
source('data_processing.r')

# GDP
gdp_reg_data = append(total_data[32], total_data[23]) %>% dataProcessing(.)
gdp_reg_data[1] = log(gdp_reg_data[1] * 1000)
pairs(gdp_reg_data)
gdp_fit = lm(greenhouse ~ ., gdp_reg_data)
summary(gdp_fit)
anova(gdp_fit)
ggplot(gdp_reg_data, aes(greenhouse, total_gdp_us_inflation_adjusted)) + geom_point() + geom_smooth(formula = y ~ x, method=lm)
par(mfrow = c(2, 2))
plot(gdp_fit)
plot(gdp_fit, which = c(4, 6))
plot(dffits(gdp_fit), main = 'diffits')
abline(h = 2*sqrt(6/63), lty = 2)
plot(covratio(gdp_fit), main = 'covratio')
abline(h = 1 + 3*6/63, lty = 2)
abline(h = 1 - 3*6/63, lty = 2)
dwtest(gdp_fit)
step(gdp_fit)

# renewable
renewable_reg_data = append(total_data[32], total_data[33]) %>% dataProcessing(.)
renewable_reg_data[1] = log(renewable_reg_data[1] * 1000)
renewable_reg_data[2] = log(renewable_reg_data[2])
is.na(renewable_reg_data) = sapply(renewable_reg_data, is.infinite)
renewable_reg_data[is.na(renewable_reg_data)] = 0
pairs(renewable_reg_data)
renewable_fit = lm(greenhouse ~ ., renewable_reg_data)
summary(renewable_fit)
anova(renewable_fit)
ggplot(renewable_reg_data, aes(greenhouse, electricity_from_renewable)) + geom_point() + geom_smooth(formula = y ~ x, method=lm)
par(mfrow = c(2, 2))
plot(renewable_fit)
plot(renewable_fit, which = c(4, 6))
plot(dffits(renewable_fit), main = 'diffits')
abline(h = 2*sqrt(6/63), lty = 2)
plot(covratio(renewable_fit), main = 'covratio')
abline(h = 1 + 3*6/63, lty = 2)
abline(h = 1 - 3*6/63, lty = 2)
dwtest(renewable_fit)
step(renewable_fit)

# energy
energy_reg_data = append(total_data[32], total_data[9:17]) %>% append(., total_data[33]) %>% dataProcessing(.)
energy_reg_data[1] = log(energy_reg_data[1] * 1000)
energy_reg_data[11] = log(energy_reg_data[11])
is.na(energy_reg_data[11]) = sapply(energy_reg_data[11], is.infinite)
energy_reg_data[is.na(energy_reg_data[11]), 11] = 0
pairs(energy_reg_data)
energy_fit = lm(greenhouse ~ ., energy_reg_data)
summary(energy_fit)
anova(energy_fit)
par(mfrow = c(2, 2))
plot(energy_fit)
plot(energy_fit, which = c(4, 6))
plot(dffits(energy_fit), main = 'diffits')
abline(h = 2*sqrt(6/63), lty = 2)
plot(covratio(gdp_fit), main = 'covratio')
abline(h = 1 + 3*6/63, lty = 2)
abline(h = 1 - 3*6/63, lty = 2)
dwtest(energy_fit)
step(energy_fit)
summary(lm(formula = greenhouse ~ coal_consumption_total + electricity_generation_total + 
             residential_electricity_use_total + natural_gas_production_total + 
             nuclear_power_generation_total + energy_production_total + 
             electricity_from_renewable, data = energy_reg_data))
