library(regbook)
library(tidyverse)
library(lmtest)
source('data_processing.r')

# material, GDP growth
first_reg_data = append(total_data[32], total_data[7]) %>% append(., total_data[20]) %>% dataProcessing(.)
first_reg_data[1] = log(first_reg_data[1] * 1000)
pairs(first_reg_data)
first_fit = lm(greenhouse ~ ., first_reg_data)
summary(first_fit)
anova(first_fit)
par(mfrow = c(2, 2))
plot(first_fit)
plot(first_fit, which = c(4, 6))
plot(dffits(first_fit), main = 'diffits')
abline(h = 2*sqrt(6/63), lty = 2)
plot(covratio(first_fit), main = 'covratio')
abline(h = 1 + 3*6/63, lty = 2)
abline(h = 1 - 3*6/63, lty = 2)
dwtest(first_fit)
step(first_fit)

# life expectancy
life_reg_data = append(total_data[32], total_data[3]) %>% dataProcessing(.)
life_reg_data[1] = log(life_reg_data[1] * 1000)
pairs(life_reg_data)
life_fit = lm(greenhouse ~ ., life_reg_data)
summary(life_fit)
anova(life_fit)
ggplot(life_reg_data, aes(greenhouse, life_expectancy_years)) + geom_point() + geom_smooth(formula = y ~ x, method=lm)
par(mfrow = c(2, 2))
plot(life_fit)
plot(life_fit, which = c(4, 6))
plot(dffits(life_fit), main = 'diffits')
abline(h = 2*sqrt(6/63), lty = 2)
plot(covratio(life_fit), main = 'covratio')
abline(h = 1 + 3*6/63, lty = 2)
abline(h = 1 - 3*6/63, lty = 2)
dwtest(life_fit)
step(life_fit)

# oil, coal consumption
second_reg_data = append(total_data[32], total_data[9]) %>% append(., total_data[15]) %>% dataProcessing(.)
second_reg_data[1] = log(second_reg_data[1] * 1000)
pairs(second_reg_data)
second_fit = lm(greenhouse ~ ., second_reg_data)
summary(second_fit)
anova(second_fit)
par(mfrow = c(2, 2))
plot(second_fit)
plot(second_fit, which = c(4, 6))
plot(dffits(second_fit), main = 'diffits')
abline(h = 2*sqrt(6/63), lty = 2)
plot(covratio(second_fit), main = 'covratio')
abline(h = 1 + 3*6/63, lty = 2)
abline(h = 1 - 3*6/63, lty = 2)
dwtest(second_fit)
step(second_fit)

# population
population_reg_data_1 = total_data[1:3] %>% dataProcessing(.)
population_reg_data_1[1] = log(population_reg_data_1[1] * 1000)
pairs(population_reg_data_1)
pop_fit_1 = lm(yearly_co2_emissions_1000_tonnes ~ ., population_reg_data_1)
summary(pop_fit_1)

population_reg_data_2 = append(total_data[31], total_data[2:3]) %>% dataProcessing(.)
population_reg_data_2[1] = log(population_reg_data_2[1] * 3.664 * 1000)
pairs(population_reg_data_2)
pop_fit_2 = lm(carbon ~ ., population_reg_data_2)
summary(pop_fit_2)

population_reg_data_3 = append(total_data[32], total_data[2:3]) %>% dataProcessing(.)
population_reg_data_3[1] = log(population_reg_data_3[1] * 1000)
pairs(population_reg_data_3)
pop_fit_3 = lm(greenhouse ~ ., population_reg_data_3)
summary(pop_fit_3)

# environment
environment_reg_data_1 = append(total_data[1], total_data[4:8]) %>% dataProcessing(.)
environment_reg_data_1[1] = log(environment_reg_data_1[1] * 1000)
pairs(environment_reg_data_1)
env_fit_1 = lm(yearly_co2_emissions_1000_tonnes ~ ., environment_reg_data_1)
summary(env_fit_1)

environment_reg_data_2 = append(total_data[31], total_data[4:8]) %>% dataProcessing(.)
environment_reg_data_2[1] = log(environment_reg_data_2[1] * 3.664 * 1000)
pairs(environment_reg_data_2)
env_fit_2 = lm(carbon ~ ., environment_reg_data_2)
summary(env_fit_2)

environment_reg_data_3 = append(total_data[32], total_data[4:8]) %>% dataProcessing(.)
environment_reg_data_3[1] = log(environment_reg_data_3[1] * 1000)
pairs(environment_reg_data_3)
env_fit_3 = lm(greenhouse ~ ., environment_reg_data_3)
summary(env_fit_3)

# energy
energy_reg_data_1 = append(total_data[1], total_data[9:17]) %>% dataProcessing(.)
energy_reg_data_1[1] = log(energy_reg_data_1[1] * 1000)
pairs(energy_reg_data_1)
energy_fit_1 = lm(yearly_co2_emissions_1000_tonnes ~ ., energy_reg_data_1)
summary(energy_fit_1)

energy_reg_data_2 = append(total_data[31], total_data[9:17]) %>% dataProcessing(.)
energy_reg_data_2[1] = log(energy_reg_data_2[1] * 3.664 * 1000)
pairs(energy_reg_data_2)
energy_fit_2 = lm(carbon ~ ., energy_reg_data_2)
summary(energy_fit_2)

energy_reg_data_3 = append(total_data[32], total_data[9:17]) %>% dataProcessing(.)
energy_reg_data_3[1] = log(energy_reg_data_3[1] * 1000)
pairs(energy_reg_data_3)
energy_fit_3 = lm(greenhouse ~ ., energy_reg_data_3)
summary(energy_fit_3)

# economy
economy_reg_data_1 = dataProcessing(append(total_data[1], total_data[18:26]))
economy_reg_data_1[1] = log(economy_reg_data_1[1] * 1000)
pairs(economy_reg_data)
economy_fit_1 = lm(yearly_co2_emissions_1000_tonnes ~ ., economy_reg_data)
summary(economy_fit_1)

economy_reg_data_2 = append(total_data[31], total_data[18:26]) %>% dataProcessing(.)
economy_reg_data_2[1] = log(economy_reg_data_2[1] * 3.664 * 1000)
pairs(economy_reg_data_2)
economy_fit_2 = lm(carbon ~ ., economy_reg_data_2)
summary(economy_fit_2)

economy_reg_data_3 = append(total_data[32], total_data[18:26]) %>% dataProcessing(.)
economy_reg_data_3[1] = log(economy_reg_data_3[1] * 1000)
pairs(economy_reg_data_3)
economy_fit_2 = lm(greenhouse ~ ., economy_reg_data_3)
summary(economy_fit_2)

# labor
labor_reg_data_1 = append(total_data[1], total_data[27:28]) %>% dataProcessing(.)
labor_reg_data_1[1] = log(labor_reg_data_1[1] * 1000)
pairs(labor_reg_data_1)
labor_fit_1 = lm(yearly_co2_emissions_1000_tonnes ~ ., labor_reg_data_1)
summary(labor_fit_1)

labor_reg_data_2 = append(total_data[31], total_data[27:28]) %>% dataProcessing(.)
labor_reg_data_2[1] = log(labor_reg_data_2[1] * 3.664 * 1000)
pairs(labor_reg_data_2)
labor_fit_2 = lm(carbon ~ ., labor_reg_data_2)
summary(labor_fit_2)

labor_reg_data_3 = append(total_data[32], total_data[27:28]) %>% dataProcessing(.)
labor_reg_data_3[1] = log(labor_reg_data_3[1] * 1000)
pairs(labor_reg_data_3)
labor_fit_3 = lm(greenhouse ~ ., labor_reg_data_3)
summary(labor_fit_3)

# society
society_reg_data_1 = dataProcessing(append(total_data[1], total_data[29:30]))
society_reg_data_1[1] = log(society_reg_data_1[1] * 1000)
pairs(society_reg_data_1)
society_fit_1 = lm(yearly_co2_emissions_1000_tonnes ~ ., society_reg_data_1)
summary(society_fit_1)

society_reg_data_2 = append(total_data[31], total_data[29:30]) %>% dataProcessing(.)
society_reg_data_2[1] = log(society_reg_data_2[1] * 3.664 * 1000)
pairs(society_reg_data_2)
society_fit_2 = lm(carbon ~ ., society_reg_data_2)
summary(society_fit_2)

society_reg_data_3 = append(total_data[32], total_data[29:30]) %>% dataProcessing(.)
society_reg_data_3[1] = log(society_reg_data_3[1] * 1000)
pairs(labor_reg_data_3)
society_fit_3 = lm(greenhouse ~ ., society_reg_data_3)
summary(society_fit_3)

second_reg_data = append(total_data[32], total_data[24:26]) %>% dataProcessing(.)
second_reg_data[1] = log(second_reg_data[1] * 1000)
pairs(second_reg_data)
second_fit = lm(greenhouse ~ ., second_reg_data)
summary(second_fit)

third_reg_data = append(total_data[32], total_data[7]) %>% dataProcessing(.)
third_reg_data[1] = log(third_reg_data[1] * 1000)
pairs(third_reg_data)
third_fit = lm(greenhouse ~ ., third_reg_data)
summary(third_fit)
ggplot(third_reg_data, aes(x=greenhouse, y=matfootp)) + geom_point() + geom_smooth(formula = y ~ x, method=lm)

forth_reg_data = append(total_data[32], total_data[3]) %>% append(., total_data[7]) %>% 
  append(., total_data[11]) %>% append(., total_data[33]) %>% append(., total_data[18:19]) %>% 
  append(., total_data[23]) %>% append(., total_data[29:30]) %>% dataProcessing(.)
forth_reg_data[1] = log(forth_reg_data[1] * 1000)
pairs(forth_reg_data)
forth_fit = lm(greenhouse ~ ., forth_reg_data)
summary(forth_fit)

fifth_reg_data = append(total_data[32], total_data[14]) %>% dataProcessing(.)
fifth_reg_data[1] = log(fifth_reg_data[1] * 1000)
pairs(fifth_reg_data)
fifth_fit = lm(greenhouse ~ ., fifth_reg_data)
summary(fifth_fit)
ggplot(fifth_reg_data, aes(x=greenhouse, y=nuclear_power_generation_total)) + geom_point() + geom_smooth(formula = y ~ x, method=lm)

sixth_reg_data = append(list(greenhouse = greenhouse_worldbank, renewable_electricity = electricity_from_renewable), total_data[10:11]) %>% dataProcessing(.)
sixth_reg_data[1] = log(sixth_reg_data[1] * 1000)
sixth_reg_data[2] = log(sixth_reg_data[2])
is.na(sixth_reg_data) = sapply(sixth_reg_data, is.infinite)
sixth_reg_data = sixth_reg_data %>% drop_na()
pairs(sixth_reg_data)
sixth_fit = lm(greenhouse ~ ., sixth_reg_data)
summary(sixth_fit)
# ggplot(sixth_reg_data, aes(x=carbon, y=renewable_electricity)) + geom_point() + geom_smooth(formula = y ~ x,, method=lm)

seventh_reg_data = append(list(greenhouse = greenhouse_worldbank), total_data[2]) %>% dataProcessing(.)
seventh_reg_data[1] = log(seventh_reg_data[1] * 1000)
pairs(seventh_reg_data)
seventh_fit = lm(greenhouse ~ ., seventh_reg_data)
summary(seventh_fit)
# step(seventh_fit, scope = ~ ., test = 'F')
